server:
  image: daocloud.io/qq08420/zyf-server:latest
  links:
  - mongo:mongo
mongo:
  image: mongo
  volumes:
  - /data/db:/data/db
static:
  image: daocloud.io/qq08420/zyf:latest
  ports:
  - 80:80
  links:
  - server:web
