web:
  image: daocloud.io/qq08420/zyf
  links:
    - mongo:mongo
mongo:
    image: mongo
    volumes:
        - /data/db:/data/db
proxy:
    image: daocloud.io/qq08420/zyf-server
    ports:
        - 80:80
    links:
        - web:web
