import express from 'express'
import React from 'react'
import {renderToString} from 'react-dom/server'
import {RoutingContext,match} from 'react-router'
import {Provider} from 'react-redux'
import store from '../src/store'