#%RAML 1.0
title: web
baseUri: http://localhost:8080/api
types:
  Article:
    type: object
    properties:
      title: string
      content: string
  User:
    type: object
    properties:
      name: string
      pass: string
/article:
  get:
    queryParameters:
      limit:
        type: number
        required: false
      skip:
        type: number
        required: false
    responses:
      200:
        body:
          application/json:
            type: Article[]
  post:
    body:
      application/json:
        type: Article
        example:
          title: "title example"
          content: "content example"
  /{id}:
    delete:
    put:
      body:
        application/json:
          type: object
          example:
            title: "233"
    get:
/user:
  /login:
    post:
      body:
        application/json:
          type: User
          example:
            name: ""
            pass: ""
  /register:
    post:
/config/{name}:
  get:
  put:
    body:
      application/json:
        type: object
        example:
          name: ""
          tel: ""
