on: push
jobs:
  my-job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: jerray/setup-aliyun-cli-action@v1.0.0
        with:
          aliyun-cli-version: '3.0.29'
          mode: AK
          access-key-id: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_REGION }}
      - run: npm install
      - run: npm run build
      - run: aliyun oss cp ./dist oss://zhouyufu/ -r -u